
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gestioneCampoTennis(object):
    def setupUi(self, gestioneCampoTennis):
        gestioneCampoTennis.setObjectName("gestioneCampoTennis")
        gestioneCampoTennis.resize(781, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gestioneCampoTennis.sizePolicy().hasHeightForWidth())
        gestioneCampoTennis.setSizePolicy(sizePolicy)
        gestioneCampoTennis.setMinimumSize(QtCore.QSize(781, 500))
        gestioneCampoTennis.setMaximumSize(QtCore.QSize(781, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/immaginelogo1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gestioneCampoTennis.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(gestioneCampoTennis)
        self.centralwidget.setObjectName("centralwidget")
        self.immaginepesi = QtWidgets.QLabel(self.centralwidget)
        self.immaginepesi.setGeometry(QtCore.QRect(130, -30, 791, 501))
        self.immaginepesi.setText("")
        self.immaginepesi.setTextFormat(QtCore.Qt.AutoText)
        self.immaginepesi.setPixmap(QtGui.QPixmap("images/immaginepesisfocata.jpeg"))
        self.immaginepesi.setScaledContents(True)
        self.immaginepesi.setAlignment(QtCore.Qt.AlignCenter)
        self.immaginepesi.setObjectName("immaginepesi")
        self.indietro = QtWidgets.QPushButton(self.centralwidget)
        self.indietro.setGeometry(QtCore.QRect(30, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 1, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 1, 13))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.indietro.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(12)
        self.indietro.setFont(font)
        self.indietro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.indietro.setIconSize(QtCore.QSize(40, 40))
        self.indietro.setDefault(False)
        self.indietro.setObjectName("indietro")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(40, 60, 521, 401))
        self.listView.setObjectName("listView")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(560, 60, 20, 401))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setInvertedAppearance(False)
        self.verticalScrollBar.setInvertedControls(True)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.visualizzaaprenotazione = QtWidgets.QPushButton(self.centralwidget)
        self.visualizzaaprenotazione.setGeometry(QtCore.QRect(600, 130, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.visualizzaaprenotazione.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.visualizzaaprenotazione.setFont(font)
        self.visualizzaaprenotazione.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.visualizzaaprenotazione.setObjectName("visualizzaaprenotazione")
        self.eliminaaprenotazione = QtWidgets.QPushButton(self.centralwidget)
        self.eliminaaprenotazione.setGeometry(QtCore.QRect(600, 190, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.eliminaaprenotazione.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eliminaaprenotazione.setFont(font)
        self.eliminaaprenotazione.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eliminaaprenotazione.setObjectName("eliminaaprenotazione")
        self.aggiungiprenotazione = QtWidgets.QPushButton(self.centralwidget)
        self.aggiungiprenotazione.setGeometry(QtCore.QRect(600, 70, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.aggiungiprenotazione.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.aggiungiprenotazione.setFont(font)
        self.aggiungiprenotazione.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aggiungiprenotazione.setObjectName("aggiungiprenotazione")
        gestioneCampoTennis.setCentralWidget(self.centralwidget)

        self.retranslateUi(gestioneCampoTennis)
        QtCore.QMetaObject.connectSlotsByName(gestioneCampoTennis)


        self.indietro.clicked.connect(gestioneCampoTennis.close)

    def retranslateUi(self, gestioneCampoTennis):
        _translate = QtCore.QCoreApplication.translate
        gestioneCampoTennis.setWindowTitle(_translate("gestioneCampoTennis", "Gestione campo da tennis"))
        self.indietro.setText(_translate("gestioneCampoTennis", "⬅️"))
        self.indietro.setShortcut(_translate("gestioneCampoTennis", "Alt+Left"))
        self.visualizzaaprenotazione.setText(_translate("gestioneCampoTennis", "Visualizza\n"
        " prenotazione"))
        self.visualizzaaprenotazione.setShortcut(_translate("gestioneCampoTennis", "Alt+Return"))
        self.eliminaaprenotazione.setText(_translate("gestioneCampoTennis", "Elimina\n"
        " prenotazione"))
        self.eliminaaprenotazione.setShortcut(_translate("gestioneCampoTennis", "Ctrl+D"))
        self.aggiungiprenotazione.setText(_translate("gestioneCampoTennis", "Aggiungi \n"
        " prenotazione"))
        self.aggiungiprenotazione.setShortcut(_translate("gestioneCampoTennis", "Ctrl+A"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     gestioneCampoTennis = QtWidgets.QMainWindow()
#     ui = Ui_gestioneCampoTennis()
#     ui.setupUi(gestioneCampoTennis)
#     gestioneCampoTennis.show()
#     sys.exit(app.exec_())
